#!/bin/sh
#
# @name SSRD Speedo Quadrotor SITL (2 kg, APC 7x11E, 10k RPM hover)
#
# @type Quadrotor Wide
#
# @maintainer Custom Configuration
#
# Working copy in speedo_ws: config/px4/airframes/10018_ssrd_speedo
# Deploy into PX4 ROMFS (see config/px4/README.md).
#

. ${R}etc/init.d/rc.mc_defaults

# Frame config from speedo2.0bacupwip.params
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_CT 6.50
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR0_PX 0.09
param set-default CA_ROTOR0_PY 0.09
param set-default CA_ROTOR0_PZ 0.03

param set-default CA_ROTOR1_CT 6.50
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_PX -0.09
param set-default CA_ROTOR1_PY -0.09
param set-default CA_ROTOR1_PZ 0.03

param set-default CA_ROTOR2_CT 6.50
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_PX 0.095
param set-default CA_ROTOR2_PY -0.09
param set-default CA_ROTOR2_PZ 0.03

param set-default CA_ROTOR3_CT 6.50
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR3_PX -0.09
param set-default CA_ROTOR3_PY 0.09
param set-default CA_ROTOR3_PZ 0.03

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# Battery: 12S LiPo (44.4V nominal, 50.4V full)
param set-default BAT1_N_CELLS 12
param set-default BAT1_V_CHARGED 4.2
param set-default BAT1_V_EMPTY 3.2
# BAT1_A_PER_V not in this PX4 version
param set-default BAT_CRIT_THR 0.20
param set-default BAT_EMERGEN_THR 0.05
param set-default BAT_LOW_THR 0.35

# IMU driver LPF + gyro notches / DNF (speedo2.0bacupwip.params). MPC_VEL_NF_* with MPC block below.
# param set-default IMU_ACCEL_CUTOFF 30.0
# param set-default IMU_DGYRO_CUTOFF 40.0
# param set-default IMU_GYRO_CUTOFF 80.0
# param set-default IMU_GYRO_DNF_BW 18.0
# param set-default IMU_GYRO_DNF_EN 1
# param set-default IMU_GYRO_DNF_HMC 2
# param set-default IMU_GYRO_DNF_MIN 90.0
# param set-default IMU_GYRO_FFT_EN 0
# param set-default IMU_GYRO_NF0_BW 20.0
# param set-default IMU_GYRO_NF0_FRQ 0.0
# param set-default IMU_GYRO_NF1_BW 20.0
# param set-default IMU_GYRO_NF1_FRQ 0.0

# MC attitude / rate PID + MPC (values from speedo2.0bacupwip.params)
param set-default MC_PITCHRATE_D 0.005
param set-default MC_PITCHRATE_FF 0.0
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_K 1.75
param set-default MC_PITCHRATE_MAX 220.0
param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCH_P 7.0
param set-default MC_PR_INT_LIM 0.3
param set-default MC_ROLLRATE_D 0.005
param set-default MC_ROLLRATE_FF 0.0
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_K 1.75
param set-default MC_ROLLRATE_MAX 220.0
param set-default MC_ROLLRATE_P 0.15
param set-default MC_ROLL_P 7.0
param set-default MC_RR_INT_LIM 0.3
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAWRATE_FF 0.0
param set-default MC_YAWRATE_I 0.0
param set-default MC_YAWRATE_K 0.3
param set-default MC_YAWRATE_MAX 360.0
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAW_P 3.0
param set-default MC_YAW_TQ_CUTOFF 2.0
param set-default MC_YAW_WEIGHT 0.4
param set-default MC_YR_INT_LIM 0.3

param set-default MPC_ACC_DECOUPLE 1
param set-default MPC_ACC_DOWN_MAX 3.0
param set-default MPC_ACC_HOR 3.0
param set-default MPC_ACC_HOR_MAX 5.0
param set-default MPC_ACC_UP_MAX 4.0
param set-default MPC_ALT_MODE 2
param set-default MPC_HOLD_MAX_XY 0.8
param set-default MPC_HOLD_MAX_Z 0.6
param set-default MPC_JERK_AUTO 4.0
param set-default MPC_JERK_MAX 8.0
param set-default MPC_LAND_ALT1 10.0
param set-default MPC_LAND_ALT2 5.0
param set-default MPC_LAND_ALT3 1.0
param set-default MPC_LAND_CRWL 0.3
param set-default MPC_LAND_RADIUS -1.0
param set-default MPC_LAND_RC_HELP 0
param set-default MPC_LAND_SPEED 0.7
param set-default MPC_MANTHR_MIN 0.08
param set-default MPC_MAN_TILT_MAX 40.0
param set-default MPC_MAN_Y_MAX 150.0
param set-default MPC_MAN_Y_TAU 0.08
param set-default MPC_POS_MODE 4
param set-default MPC_THR_CURVE 0
param set-default MPC_THR_HOVER 0.21
param set-default MPC_THR_MAX 1.0
param set-default MPC_THR_MIN 0.12
param set-default MPC_THR_XY_MARG 0.3
param set-default MPC_TILTMAX_AIR 45.0
param set-default MPC_TILTMAX_LND 12.0
# Fast takeoff ramp / climb for sim (see multicopter_takeoff_land_params).
param set-default MPC_TKO_RAMP_T 0.5
param set-default MPC_TKO_SPEED 5.0
param set-default MPC_VELD_LP 5.0
param set-default MPC_VEL_LP 0.0
param set-default MPC_VEL_MANUAL 10.0
param set-default MPC_VEL_MAN_BACK -1.0
param set-default MPC_VEL_MAN_SIDE -1.0
param set-default MPC_VEL_NF_BW 5.0
param set-default MPC_VEL_NF_FRQ 0.0
param set-default MPC_XY_CRUISE 5.0
param set-default MPC_XY_VEL_P_ACC 4.5

param set-default MPC_XY_ERR_MAX 2.0
param set-default MPC_XY_P 1.5
param set-default MPC_XY_TRAJ_P 0.5
param set-default MPC_XY_VEL_ALL -10.0
param set-default MPC_XY_VEL_D_ACC 0.1
param set-default MPC_XY_VEL_I_ACC 1.0
param set-default MPC_XY_VEL_MAX 12.0
param set-default MPC_YAWRAUTO_ACC 20.0
param set-default MPC_YAWRAUTO_MAX 60.0
param set-default MPC_YAW_MODE 0
param set-default MPC_Z_P 1.0
param set-default MPC_Z_VEL_ALL -3.0
param set-default MPC_Z_VEL_D_ACC 0.05
param set-default MPC_Z_VEL_I_ACC 2.4
# Z_VEL_MAX_* raised for sim tracking; Z_VEL_MAX_DN above typical offboard descent cap.
param set-default MPC_Z_VEL_MAX_DN 1.5
param set-default MPC_Z_VEL_MAX_UP 3.0
param set-default MPC_Z_VEL_P_ACC 10.0
param set-default MPC_Z_V_AUTO_DN 1.5
param set-default MPC_Z_V_AUTO_UP 3.0
# SITL: shorter post-arm idle window (increase for real hardware / prop checks).
param set-default COM_SPOOLUP_TIME 0.5
# Keep PX4 on simulation time (HIL timestamps)
param set-default UXRCE_DDS_SYNCT 0

# Offboard/swarm: no RC required
param set COM_RC_IN_MODE 1
param set NAV_RCL_ACT 0
param set COM_RCL_EXCEPT 4
param set COM_RC_OVERRIDE 0
